-- ============================================================================
-- ParkGo — Financial Report support
-- Run this in the Supabase SQL editor (project unvzbszdocfmcfpguvrc).
--
-- Adds two tables:
--   1. facility_expense       — the manager-editable monthly cost line items
--                               (fixed salaries, electricity, maintenance, and
--                               the per-visit technician fee). A single row of
--                               id = 1 holds the current amounts so the manager
--                               can adjust them for the whole facility.
--   2. maintenance_event      — one row per technician/maintenance call, used to
--                               count the *variable* expense (how many times a
--                               technician was called in a given month).
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 1) Editable expense configuration (single-row config table, id = 1)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.facility_expense (
  id                  integer      NOT NULL DEFAULT 1,
  guard_salary        numeric      NOT NULL DEFAULT 5000,   -- monthly, fixed
  manager_salary      numeric      NOT NULL DEFAULT 12000,  -- monthly, fixed
  electricity         numeric      NOT NULL DEFAULT 600,    -- monthly, fixed
  facility_upkeep     numeric      NOT NULL DEFAULT 1000,   -- monthly, fixed
  technician_fee      numeric      NOT NULL DEFAULT 600,    -- per technician call (variable)
  updated_at          timestamptz  NOT NULL DEFAULT now(),
  CONSTRAINT facility_expense_pkey PRIMARY KEY (id),
  CONSTRAINT facility_expense_singleton CHECK (id = 1)
);

-- Seed the single configuration row with the default amounts.
INSERT INTO public.facility_expense (id)
VALUES (1)
ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- 2) Technician / maintenance call log (variable expense driver)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.maintenance_event (
  event_id     bigint       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  called_at    timestamptz  NOT NULL DEFAULT now(),
  called_by    varchar,
  note         varchar,
  CONSTRAINT maintenance_event_pkey PRIMARY KEY (event_id)
);

-- Query pattern is "how many calls in month X" → index the timestamp.
CREATE INDEX IF NOT EXISTS maintenance_event_called_at_idx
  ON public.maintenance_event (called_at);
